FROM python:3.9

WORKDIR /app



COPY requirements_preprocessing.txt ./
RUN pip install --no-cache-dir -r requirements_preprocessing.txt

COPY . .

CMD ["/bin/sh", "-c", "uvicorn main_sales_preprocessing:app --host 0.0.0.0 --port 8080"]